# Task 1: Data Inspection and Preparation

## a) Understanding and Pruning the Data

loading the data

In [2]:
import pandas as pd

orders = pd.read_csv('orders.csv')
order_products = pd.read_csv('order_products.csv')
aisles = pd.read_csv('aisles.csv')
products = pd.read_csv('products.csv')
departments = pd.read_csv('departments.csv')

checking heads

In [5]:
display(orders.head())
display(order_products.head())
display(aisles.head())
display(products.head())
display(departments.head())

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

sampling users

In [8]:
SEED = 333

# original item counts
print("BEFORE FILTERING")
print(f"len(orders): {len(orders)}")
print(f"len(order_products): {len(order_products)}")

# random sampling
sample_user_id = orders['user_id'].drop_duplicates().sample(n=10000, random_state=SEED)

# filter using the sampling
orders_reduced = orders[orders['user_id'].isin(sample_user_id)]
order_products_reduced = order_products[order_products['order_id'].isin(orders_reduced['order_id'])]

# new item counts
print("AFTER FILTERING")
print(f"len(orders): {len(orders_reduced)}")
print(f"len(order_products): {len(order_products_reduced)}")

BEFORE FILTERING
len(orders): 3421083
len(order_products): 33819106
AFTER FILTERING
len(orders): 164035
len(order_products): 1625000

constructing transactions

In [9]:
# merge with products (for product names)
df_merged = order_products_reduced.merge(products[['product_id', 'product_name']], on='product_id')

# group by order number
transactions = df_merged.groupby('order_id')['product_name'].apply(list).values.tolist()

# check head
print("example transaction:")
print(transactions[SEED])

example transaction:
['Smartwater', 'Ginger Beer', 'Pure Irish Butter', 'Dha Omega 3 Vitamin D Milk', 'Selects Smoked Uncured Bacon', 'Green Beans', 'Turkey Bacon', 'Baby Spinach', 'Thick Cut Bacon', 'Red Peppers', 'Hazelnut Spread With Skim Milk & Cocoa', 'Veri Veri Teriyaki Marinade & Sauce', 'Traditional Favorites Tomato & Basil Pasta Sauce', 'Sliced Provolone Cheese', 'Freshly Shaved Parmesan Cheese', 'Organic Yellow Onion']